language: ruby
rvm:
 - 2.3.0
services:
  - postgresql
before_script:
  - psql -c 'create database store_development;' -U postgres
  - sudo apt-get install libqt4-dev libqtwebkit-dev
  - "export DISPLAY=:99.0" 
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3